const properties = [
    {
        id: 1,
        title: "Luxury Beachfront Villa",
        location: "Malibu, CA",
        price: "$8,900,000",
        beds: 6,
        baths: 7,
        sqft: "7,800",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811",
        type: "Sale",
        featured: true,
        amenities: ["Pool", "Beach Access", "Smart Home", "Wine Cellar"]
    },
    {
        id: 2,
        title: "Modern Skyline Penthouse",
        location: "Manhattan, NY",
        price: "$6,500,000",
        beds: 4,
        baths: 4.5,
        sqft: "4,200",
        image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
        type: "Sale",
        featured: true,
        amenities: ["Doorman", "Gym", "Terrace", "Private Elevator"]
    },
    {
        id: 3,
        title: "Contemporary Lake House",
        location: "Lake Tahoe, NV",
        price: "$12,000/month",
        beds: 5,
        baths: 5,
        sqft: "5,500",
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
        type: "Rent",
        featured: true,
        amenities: ["Lake View", "Dock", "Hot Tub", "Game Room"]
    },
    {
        id: 4,
        title: "Mediterranean Estate",
        location: "Beverly Hills, CA",
        price: "$15,500,000",
        beds: 8,
        baths: 10,
        sqft: "12,000",
        image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
        type: "Sale",
        featured: false,
        amenities: ["Theater", "Tennis Court", "Guest House", "Security"]
    },
    {
        id: 5,
        title: "Downtown Loft",
        location: "Chicago, IL",
        price: "$8,500/month",
        beds: 2,
        baths: 2,
        sqft: "2,200",
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
        type: "Rent",
        featured: false,
        amenities: ["Exposed Brick", "High Ceilings", "City Views", "Parking"]
    },
    {
        id: 6,
        title: "Mountain View Retreat",
        location: "Aspen, CO",
        price: "$7,200,000",
        beds: 6,
        baths: 7,
        sqft: "6,800",
        image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233",
        type: "Sale",
        featured: false,
        amenities: ["Ski Access", "Heated Driveway", "Wine Room", "Spa"]
    }
];
